Update TransactionalDatabase.py
UdayLab/PAMI pull request #409
Opened 2024-05-06 22:39 UTC by Tarun-Sreepada

2024-05-06 23:45 UTC, udayRage requested changes
Have you checked the correctness of the new code?

It is still in-correct.

The items are separated by comma, even though we give tab space.

2024-05-06 23:59 UTC, Tarun-Sreepada commented
Yes. I have. May I see the code that you have used professor?

2024-05-07 07:39 UTC, udayRage approved these changes

2024-05-07 07:42 UTC, udayRage approved these changes

2024-05-07 07:42 UTC, merged